import type { PromptCategory, PromptTag, Prompt } from "@/lib/prompt-types"

export const promptCategories: PromptCategory[] = [
  { id: "all", label: "Tất cả", emoji: "" },
  { id: "abstract", label: "Abstract", emoji: "🎨" },
  { id: "animation", label: "Animation", emoji: "✨" },
  { id: "anime", label: "Palette Anime", emoji: "🌸" },
  { id: "ban-hang", label: "Bán hàng", emoji: "🛒" },
  { id: "cinematic", label: "Cinematic", emoji: "🎬" },
  { id: "facebook", label: "Facebook", emoji: "📘" },
  { id: "marketing", label: "Marketing", emoji: "📣" },
  { id: "nature", label: "Nature", emoji: "🌿" },
  { id: "portrait", label: "Portrait", emoji: "👤" },
  { id: "product", label: "Sản phẩm", emoji: "📦" },
  { id: "food", label: "Ẩm thực", emoji: "🍜" },
  { id: "logo", label: "Logo", emoji: "💡" },
]

export const promptTags: PromptTag[] = [
  "3d render", "Landscape painting", "Van Gogh", "Video", "agriculture",
  "ai image prompt", "ao dai", "bán hàng", "bản vẽ kỹ thuật ai", "clean food",
  "confectionery", "diorama", "drinks", "fashion", "food photography",
  "interior design", "jewelry", "mockup", "nature", "packaging",
  "portrait", "product photography", "real estate", "street food", "vintage",
]

export const prompts: Prompt[] = [
  {
    id: "p1",
    title: "Tạo ảnh sản phẩm phong cách thiên nhiên hùng vĩ",
    category: "product",
    categoryLabel: "Bán hàng",
    tags: ["marketing", "natural", "product photography"],
    description: "Prompt tạo ảnh sản phẩm phong cách thiên nhiên hùng vĩ siêu thực giúp tăng tính thẩm mỹ và chuyên nghiệp cho ảnh sản phẩm.",
    promptText: "Epic commercial product photography of [Nhập tên sản phẩm], perched on a rugged cliff edge at high altitude, surrounded by a majestic sea of clouds and atmospheric mist, dramatic...",
    likes: 33,
    views: 0,
    copies: 11,
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&q=80",
    color: "#1a1a2e",
  },
  {
    id: "p2",
    title: "Tạo ảnh công thức nấu ăn theo phong cách nghệ thuật diorama",
    category: "food",
    categoryLabel: "Thiết kế",
    tags: ["food", "recipes", "diorama"],
    description: "Prompt tạo ảnh công thức nấu ăn theo phong cách nghệ thuật sắp đặt mô hình thu nhỏ (Diorama) kết hợp với chữ viết tay.",
    promptText: "Task: Based on the image or information [Nhập tên món ăn] provided by the user, create me a surreal 4:5 macro close-up photograph of an oversized ancient culinary book, open 88%...",
    likes: 58,
    views: 0,
    copies: 11,
    image: "https://images.unsplash.com/photo-1589778655375-3e622c9db71b?w=400&q=80",
    color: "#16213e",
  },
  {
    id: "p3",
    title: "Tạo video quảng cáo sản phẩm đồ uống chuẩn studio",
    category: "ban-hang",
    categoryLabel: "Bán hàng",
    tags: ["product advertising"],
    description: "Prompt tạo video quảng cáo sản phẩm đồ uống chuẩn studio hoàn toàn miễn phí. Hướng dẫn chi tiết với các thông số cụ thể...",
    promptText: '"A 15-second cinematic product commercial, dark studio background, high-end lighting. BGM: Upbeat modern EDM, beat drop at 3s. —',
    likes: 7,
    views: 0,
    copies: 2,
    image: "https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=400&q=80",
    color: "#0f0f1a",
  },
  {
    id: "p4",
    title: "Tạo ảnh mon ăn ngày Tết truyền thống Việt Nam",
    category: "food",
    categoryLabel: "Bán hàng",
    tags: ["food", "recipes", "traditional"],
    description: "Prompt tạo ảnh món ăn ngày Tết theo phong cách truyền thống Việt Nam với màu sắc rực rỡ, bánh chưng, hoa đào...",
    promptText: "Cinematic overhead shot of Vietnamese Tet traditional food arrangement, bánh chưng wrapped in banana leaves, red lanterns, peach blossoms...",
    likes: 92,
    views: 0,
    copies: 11,
    image: "https://images.unsplash.com/photo-1569468066670-f62abf6cb905?w=400&q=80",
    color: "#1a0a0a",
  },
  {
    id: "p5",
    title: "Tạo logo thương hiệu tối giản hiện đại",
    category: "logo",
    categoryLabel: "Thiết kế",
    tags: ["logo", "brand", "minimal"],
    description: "Prompt tạo logo thương hiệu phong cách tối giản hiện đại. Phù hợp cho startup, thương hiệu cá nhân và doanh nghiệp vừa và nhỏ.",
    promptText: "Minimalist modern logo design for [brand name], flat vector style, clean geometric shapes, professional color palette of navy blue and gold...",
    likes: 145,
    views: 0,
    copies: 23,
    image: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&q=80",
    color: "#0a1628",
  },
  {
    id: "p6",
    title: "Chụp ảnh chân dung nghệ thuật cinematic",
    category: "portrait",
    categoryLabel: "Portrait",
    tags: ["portrait", "cinematic"],
    description: "Prompt chụp ảnh chân dung nghệ thuật theo phong cách cinematic với ánh sáng kịch tính, phù hợp cho nhiếp ảnh chuyên nghiệp.",
    promptText: "Cinematic portrait photography of [subject], dramatic Rembrandt lighting, shallow depth of field, film grain, muted color grading, 85mm lens...",
    likes: 211,
    views: 0,
    copies: 34,
    image: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&q=80",
    color: "#1a0a1a",
  },
  {
    id: "p7",
    title: "Thiết kế bao bì sản phẩm cao cấp 3D",
    category: "product",
    categoryLabel: "Sản phẩm",
    tags: ["packaging", "3d render", "product"],
    description: "Prompt thiết kế bao bì sản phẩm cao cấp với render 3D siêu thực, phù hợp cho mỹ phẩm, thực phẩm, đồ uống.",
    promptText: "Photorealistic 3D product packaging mockup of [product name], luxury premium design, soft studio lighting, white background, ray tracing...",
    likes: 67,
    views: 0,
    copies: 8,
    image: "https://images.unsplash.com/photo-1586495777744-4e6232bf3f3f?w=400&q=80",
    color: "#0a1a0a",
  },
  {
    id: "p8",
    title: "Ảnh phong cảnh thiên nhiên Van Gogh style",
    category: "abstract",
    categoryLabel: "Abstract",
    tags: ["Van Gogh", "Landscape painting", "art"],
    description: "Prompt tạo ảnh phong cảnh theo phong cách Van Gogh với nét vẽ xoáy ấn tượng, màu sắc rực rỡ đặc trưng.",
    promptText: "Stunning landscape painting in the style of Vincent van Gogh, swirling brushstrokes, vivid complementary colors of ultramarine blue and brilliant yellow...",
    likes: 189,
    views: 0,
    copies: 29,
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&q=80",
    color: "#1a1500",
  },
  {
    id: "p9",
    title: "Tạo ảnh đồ uống menu nhà hàng",
    category: "food",
    categoryLabel: "Bán hàng",
    tags: ["drinks", "food photography", "menu"],
    description: "Cách tạo ảnh đồ ăn bằng AI chuẩn studio để làm ảnh marketing. Bước 1 vào gemini hoặc chatgpt chuyể...",
    promptText: "Design a modern, premium, and highly eye-catching beverage infographic presented in Vietnamese. The main product is [TÊN ĐỒ UỐNG], shown in a transparent or semi-...",
    likes: 92,
    views: 0,
    copies: 4,
    image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400&q=80",
    color: "#0a0a1a",
  },
  {
    id: "p10",
    title: "Tạo ảnh thời trang lookbook ngoài trời",
    category: "portrait",
    categoryLabel: "Portrait",
    tags: ["fashion", "portrait", "outdoor"],
    description: "Prompt tạo ảnh thời trang phong cách lookbook chụp ngoài trời với ánh sáng tự nhiên. Phù hợp cho brand thời trang.",
    promptText: "High-fashion outdoor lookbook photography, model wearing [describe outfit], golden hour natural lighting, editorial photography style, shot on Hasselblad...",
    likes: 76,
    views: 0,
    copies: 12,
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400&q=80",
    color: "#0a0f1a",
  },
  {
    id: "p11",
    title: "Trang trí nội thất phong cách Japandi tối giản",
    category: "abstract",
    categoryLabel: "Thiết kế",
    tags: ["interior design", "minimal", "japandi"],
    description: "Prompt tạo ảnh nội thất phong cách Japandi — kết hợp giữa phong cách Nhật Bản và Scandinavia, tối giản nhưng ấm cúng.",
    promptText: "Architectural interior photography of a Japandi living room, wabi-sabi aesthetic, natural materials (oak wood, linen, rattan), neutral warm tones...",
    likes: 134,
    views: 0,
    copies: 19,
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&q=80",
    color: "#1a1508",
  },
  {
    id: "p12",
    title: "Tạo nội dung Facebook Ad chuẩn đổi người dùng",
    category: "marketing",
    categoryLabel: "Marketing",
    tags: ["facebook", "marketing", "ads"],
    description: "Prompt tạo nội dung quảng cáo Facebook chuyên nghiệp, tối ưu tỉ lệ chuyển đổi với cấu trúc AIDA.",
    promptText: "Write a high-converting Facebook ad copy for [product/service] targeting [audience]. Use AIDA framework: Attention (hook), Interest (benefits), Desire (social proof)...",
    likes: 203,
    views: 0,
    copies: 45,
    image: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=400&q=80",
    color: "#00091a",
  },
]
